### ISSUE TITLE
Unable to install package in Filament 3.X

### ISSUE THREAD

**Issue by pritborteam** [ryangjchandler/filament-navigation#110]
I am unable to install this package in latest Filament 3.X. Error says it needs Filament 2.X version .

**Comment by ryangjchandler** [comment]
Install v1.0.0-beta5. That has v3 support.

**Comment by pritborteam** [comment]
> Install v1.0.0-beta5. That has v3 support.

hi Ryan.. thanks it installed fine. But I dint find Navigation menu displaying in my admin panel. I dint even find Navigation resource. i checked the package. Model and migration is fine. Do i need to manually create Navigation resource in Admin panel selecting your model.

**Comment by ryangjchandler** [comment]
You need to make sure you register the `Plugin` in your PanelProvider class.

**Comment by pritborteam** [comment]
> You need to make sure you register the `Plugin` in your PanelProvider class.

It is already registered in my Admin panel.  But I don't see any NavigationResource anywhere.    Do I need to run any publish command further. I rerun publish asset.

**Comment by pritborteam** [comment]
Hi Ryan, I got it working. I reinstalled it. I realized that i should  have installed the plugin, then register immediately in panel provider. And then migrate and asset publish.  In previous attempts, I was doing registration after migration. Thanks.
