### ISSUE TITLE
Please add the ability for localization!

### ISSUE THREAD

**Issue by ryangjchandler** [ryangjchandler/filament-navigation#13]
### Discussed in https://github.com/ryangjchandler/filament-navigation/discussions/12

<div type='discussions-op-text'>

<sup>Originally posted by **yammycode** June  8, 2022</sup>
Please add the ability for localization!</div>

**Comment by koupisbean** [comment]
@ryangjchandler hows review going? Would need that translation asap for my project.

**Comment by ryangjchandler** [comment]
@koupisbean This is now merged - it will be released later today. Thanks!
