### ISSUE TITLE
Menu Item Order

### ISSUE THREAD

**Issue by awcodes** [ryangjchandler/filament-navigation#3]
Not sure if this is an issue just on my machine or not, but when saving a menu it appears that the UUID is causing the JSON column to default sort the menu items in ascending order (for indexing purposes, I believe). This prevents the menu item order from being preserved.

This can be seen by saving a menu then just refreshing the page.

**Comment by ryangjchandler** [comment]
@awcodes I can't seem to reproduce this problem.. can you record a video and also send over your model configuration?

**Comment by awcodes** [comment]
The model is the one in the package, i'm not doing anything with it outside of the package.

https://user-images.githubusercontent.com/3596800/164508319-1b599647-9b7f-43f9-b086-7767bd4a889d.mov

**Comment by ryangjchandler** [comment]
What database are you using?

**Comment by awcodes** [comment]
MySQL 5.7

Looks like the issue is related to this [https://dev.mysql.com/doc/refman/5.7/en/json.html#json-comparison](https://dev.mysql.com/doc/refman/5.7/en/json.html#json-comparison)

**Comment by awcodes** [comment]
I have verified that the package is maintaining the correct order before saving, so this is definitely a database issue with JSON columns, and not an issue with the plugin itself.

**Comment by awcodes** [comment]
Works perfectly with a longText column and an array cast, but i'm sure you have a reason for using the JSON column.

I'll go ahead and close this, but maybe a note in the Readme would help others in the future.

Thanks for your feedback and patience.

**Comment by ryangjchandler** [comment]
Ah, interesting... perhaps I'll move to use a longText then for compatibility reasons...

**Comment by ryangjchandler** [comment]
@awcodes I've just released v0.2.0 with a fix for this (changing column to longText), you'll need to run a `migrate` to get the changes.

You should also publish the assets again and clear your view cache to get the latest CSS changes from your dark mode PR.

Thanks!

**Comment by awcodes** [comment]
@ryangjchandler Awesome. Thanks again for all you do.
