### ISSUE TITLE
Registering new types does not work when using "laravel/octane"

### ISSUE THREAD

**Issue by BelyaevAD** [ryangjchandler/filament-navigation#52]
Hello, @ryangjchandler 

Registering new types "FilamentNavigation::addItemType()" does not work through AppServiceProvider when using "laravel/octane" and roadrunner

**Comment by ryangjchandler** [comment]
@BelyaevAD Are you on the latest version?

**Comment by BelyaevAD** [comment]
Yes, all packages have latest version.
![image](https://user-images.githubusercontent.com/6249570/201560557-24672526-6027-44fa-853b-329562514fc4.png)

Tried doing the following steps:
`composer run-script post-autoload-dump
composer run-script post-update-cmd
sail artisan optimize:clear`

I use sail+octane+roadrunner in production.

And it works correctly through tinker:
![image](https://user-images.githubusercontent.com/6249570/201562401-10b0e2f2-9c02-4ff2-b83b-bce826787c38.png)


Maybe the problem is this: https://github.com/livewire/livewire/pull/3987

**Comment by ryangjchandler** [comment]
Hm, that shouldn't be a problem. The singleton is bound as a `scoped` singleton meaning it only lasts as long as a single request, even inside of Octane...

**Comment by BelyaevAD** [comment]
To work properly, you need to use Filament::serving

I recommend adding this to the documentation.

Example:

add in `App\Providers\AppServiceProvider`:
```
    public function boot()
    {
        Filament::serving(function () {
            FilamentNavigation::addItemType('Routes', [
                Select::make('route')
                    ->searchable()
                    ->options(function () {
                        return Helper::routeList();
                    }),
                TextInput::make('params')->label('explode params by separator "|" '),
            ]);

            FilamentNavigation::addItemType('BlogCategories', [
                Select::make('list')
                    ->multiple()
                    ->options(function () {
                        return Helper::blogCategories();
                    }),
            ]);
        });
```

**Comment by ryangjchandler** [comment]
Feel free to open a PR!
