### ISSUE TITLE
addItemType breaks translations

### ISSUE THREAD

**Issue by kanknank** [ryangjchandler/filament-navigation#58]
I found a strange bug. FilamentNavigation::addItemType breaks translations of buttons and placeholders on select. If you change Select to TextInput, everything is fine.

![image](https://user-images.githubusercontent.com/58610664/206472335-493c420d-a857-4810-a4f5-66692c8ee3a3.png)
![image](https://user-images.githubusercontent.com/58610664/206472484-accc95fc-95b0-46c5-a7f8-023d0dcc4bd7.png)
![image](https://user-images.githubusercontent.com/58610664/206472666-bd9159e1-95d9-4f90-8ffd-96462886e7ab.png)

**Comment by ryangjchandler** [comment]
Thanks, I'll investigate this later today.

**Comment by kaitwalla** [comment]
Having this same issue; interestingly, it also breaks translations elsewhere (for example, on the RichEditor fields in completely separate areas of Filament). Any ideas/ETA on a fix?

**Comment by kaitwalla** [comment]
Well, shows what I know. If you register the custom types in `AppServiceProvider::boot` and they work fine.
