### ISSUE TITLE
Livewire issues when accessing menu

### ISSUE THREAD

**Issue by richdynamix** [ryangjchandler/filament-navigation#90]
@ryangjchandler 

I am encountering an issue when using the latest version of the package on a fresh install of Filament 3 where only the overlay appears when you click "Add Item" or try to edit an existing item. The form is missing.

Is there something I have missed in the setup?

<img width="1725" alt="Screenshot 2023-08-25 at 17 34 28" src="https://github.com/ryangjchandler/filament-navigation/assets/1104549/bde1bd08-cf2d-4f66-b8c3-fe908756cdf4">

**Comment by anonym-uz** [comment]
@ryangjchandler

**Comment by ryangjchandler** [comment]
> @ryangjchandler

Please do not bump an issue by ping me directly.

**Comment by ryangjchandler** [comment]
I'm currently on vacation and won't be able to look at this problem until Tuesday.

**Comment by richdynamix** [comment]
Apologies @ryangjchandler I managed to get this working and forgot to update the ticket. I wiped my plugin configuration and rewrote it which enabled me to get it working. I can only assume there was some sort of "syntax" issue here that didn't register at the PHP level.
